---
- hosts: introducer:connect
  gather_facts: no
  vars:
      repo_name: ece428
      repo_url: https://gitlab+deploy-token-23:pxBVyuFxHyRpvy7riw4D@gitlab.engr.illinois.edu/azhang38/cs425-mp3.git
      repo_remote: origin
      repo_branch: master
      git_directory: /home/dphuang2
      service_path: ansible/aystemd/ece428.service
      service_directory: /usr/lib/systemd/system/
      java_main_class: Server
  tasks:
      - name: get the code
        git: repo={{repo_url}} dest={{git_directory}}/{{repo_name}} version={{repo_branch}}
      - name: install systemd service
        command: "cp {{git_directory}}/{{repo_name}}/{{service_path}} {{service_directory}}"
