---
- hosts: introducer:connect
  gather_facts: no
  vars:
      repo_name: mp2
      repo_url: https://gitlab+deploy-token-16:Lky-dn-x7deXyGV78dAY@gitlab.engr.illinois.edu/azhang38/cs425-mp2.git
      repo_remote: origin
      repo_branch: master
      git_directory: /home/dphuang2/
      java_main_class: Server
  tasks:
      - name: get the code
        git: repo={{repo_url}} dest={{git_directory}}/{{repo_name}} version={{repo_branch}}
      - name: remake files
        make:
            chdir: "{{git_directory}}/{{repo_name}}"

- hosts: introducer
  gather_facts: no
  tasks:
      - name: restart server
        become: yes
        shell: systemctl restart mp2

- hosts: connect
  gather_facts: no
  tasks:
      - name: restart server
        become: yes
        shell: systemctl restart mp2
